spring:
  datasource:
    url: jdbc:mysql://localhost:3306/getyourway
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    physical_naming_strategy: org.hibernate.boot.entities.naming.PhysicalNamingStrategyStandardImpl
    default_catalog: getyourway
    hibernate:
      ddl-auto: none
    show-sql: false

  liquibase:
    enabled: false
    change-log: classpath:db/changelog/changelog-master.xml


logging:
  level:
    org:
      springframework:
        web: INFO

amadeus:
  air-api:
    client:
      id: mO4T2RnMd88XkgdwtvUqhHv3mR3UTmEg
      secret: GSrAA4rTvhMPCAJg
      grant_type: client_credentials
      url: https://test.api.amadeus.com

jwt:
  token:
    expiration: 1800  #30min session expiry
    secret: MzMzYjg3YTRmYmU0YmM4YzJkZWE4NTJlZGEzMDgzZjkzOWNjM2MwMWQ4NzI2MjgwZWU0MzM5ZTY0MGEzMjg1YzIwMjU1MWM5ZTNkMzg5YWNiMjExNGJlMTE4NjZlMWMxODIxNjYwMTBkZTRiZWRlNzU3MDc5ZThhMDcxMjlkMGE

server:
  port: 8090

